### ISSUE TITLE
Please add a license and screen shot

### ISSUE THREAD

**Issue by unixorn** [rmsam/boring-ohmyzsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

**Comment by rmsam** [comment]
Hi. Apologies for the late reply, but I missed the notification. Sure, no problem, but the hint is in the name: there's nothing special about this theme, quite the opposite... ;)

**Comment by rmsam** [comment]
All done, so I'm closing ;)
